# Generated by Django 2.2.6 on 2019-12-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_auto_20191124_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='pic',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
