# Generated by Django 2.2.6 on 2019-12-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='email',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
